sudo: false

language: php

php:
  - 5.6
  - 7
  - hhvm
  - nightly

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

env:
  matrix:
    - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - DEPENDENCIES=""

allow_failures:
  - php: nightly

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update -o --prefer-source $DEPENDENCIES
  - composer show

script:
  - mkdir -p build/logs
  # Run tests
  - php ./vendor/bin/phpunit --configuration tests/phpunit.xml

after_script:
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then php vendor/bin/coveralls -v; fi