language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  matrix:
    - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - DEPENDENCIES=""

before_script:
  - composer self-update
  - composer update

script:
  - mkdir -p build/logs
  # Run tests
  - php ./vendor/bin/phpunit --configuration tests/phpunit.xml

after_script:
  - php vendor/bin/coveralls -v
